### ISSUE TITLE
Emission inventory example files

### ISSUE THREAD

**Issue by joesalamoneiii** [dlr-pa/oac#1]
Thank you kindly for creating this repository.

Would it be possible to please add the emissions inventory netcdf rnd_inv files to the “repository” directory for the years listed in the example file?

Thanks and kind regards.
Joe S.

**Comment by stefan-voelk** [comment]
Dear Joe,
thank you for your message. Please follow the instructions in the README in order to create the emission inventories with artificial data:

cd utils/
python create_artificial_inventories.py

We do not plan to upload emission inventories to the Github repository since the files sizes can be large. By adapting the script you have the possibility for tailoring the inventories to your needs. There is also the possibility to download more realistic inventories from zenodo as described in the README.
Best regards,
Stefan

**Comment by joesalamoneiii** [comment]
Hello Stefan,
Thank you for the very quick response.  And I am sorry for the oversights on my part.  I will refer to the appropriate elements as you described.

Your development of this repo is very much appreciated.

Best Regards,
Joe S.
